[package]
name = "ray"
version = "0.1.0"
authors = ["eino"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.vec3]
path = "../vec3"
[lib]
path = "src/ray.rs"
